In [8]:
import numpy as np
import pandas as pd

data = {'食物':['培根','豬肉','培根','熏牛肉','咸牛肉','培根','熏牛肉','蜂蜜火腿','熏鮭魚'],
        '重量':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]}
dataFrame = pd.DataFrame(data)
dataFrame

     食物    重量
0    培根   4.0
1    豬肉   3.0
2    培根  12.0
3   熏牛肉   6.0
4   咸牛肉   7.5
5    培根   8.0
6   熏牛肉   3.0
7  蜂蜜火腿   5.0
8   熏鮭魚   6.0

In [9]:
display(dataFrame['食物'])
for item in dataFrame['食物']:
    print(item)

0      培根
1      豬肉
2      培根
3     熏牛肉
4     咸牛肉
5      培根
6     熏牛肉
7    蜂蜜火腿
8     熏鮭魚
Name: 食物, dtype: object

培根
豬肉
培根
熏牛肉
咸牛肉
培根
熏牛肉
蜂蜜火腿
熏鮭魚

In [10]:
mean_to_animal ={
    '培根':'豬',
    '豬肉':'豬',
    '熏牛肉':'牛',
    '咸牛肉':'牛',
    '蜂蜜火腿':'豬',
    '熏鮭魚':'鮭魚'
}

In [11]:
dataFrame['食物'].map(mean_to_animal)

0     豬
1     豬
2     豬
3     牛
4     牛
5     豬
6     牛
7     豬
8    鮭魚
Name: 食物, dtype: object

In [12]:
dataFrame['動物'] = dataFrame['食物'].map(mean_to_animal)
dataFrame

     食物    重量  動物
0    培根   4.0   豬
1    豬肉   3.0   豬
2    培根  12.0   豬
3   熏牛肉   6.0   牛
4   咸牛肉   7.5   牛
5    培根   8.0   豬
6   熏牛肉   3.0   牛
7  蜂蜜火腿   5.0   豬
8   熏鮭魚   6.0  鮭魚

In [15]:
def cal(value):
    return value*1.05

dataFrame['重量%5']= dataFrame['重量'].map(cal)
dataFrame

     食物    重量  動物    重量%5
0    培根   4.0   豬   4.200
1    豬肉   3.0   豬   3.150
2    培根  12.0   豬  12.600
3   熏牛肉   6.0   牛   6.300
4   咸牛肉   7.5   牛   7.875
5    培根   8.0   豬   8.400
6   熏牛肉   3.0   牛   3.150
7  蜂蜜火腿   5.0   豬   5.250
8   熏鮭魚   6.0  鮭魚   6.300