In [5]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))

def site(value:int)->str:
    return f"座號{value}"

scores_df.index = scores_df.index.map(site)
scores_df.index.name = "座號"
scores_df.columns.name="科目"
scores_df

科目    國文   英文  數學  地理   歷史
座號
座號1   58   73  55  86   50
座號2   50   63  67  98   98
座號3   50   77  61  87   56
座號4   70   95  53  92   68
座號5   56   93  58  88   52
座號6   55   60  97  94   83
座號7   85   56  84  68   86
座號8   53   65  83  51  100
座號9   50   66  95  95   60
座號10  72   96  62  70   66
座號11  54   52  57  52   64
座號12  53   71  60  77   93
座號13  59   51  60  57   58
座號14  55   55  75  95   83
座號15  60   67  66  80   89
座號16  90  100  81  70   54
座號17  75   82  61  63   50
座號18  84   86  90  55   60
座號19  69   86  95  55   90
座號20  89   58  83  98   53
座號21  54   86  82  72   97
座號22  63   98  92  71   92
座號23  77   77  99  85   55
座號24  54   95  68  75   72
座號25  89   51  70  78   53
座號26  66   77  63  89   90
座號27  75   98  87  73   52
座號28  82   63  63  63   83
座號29  64   61  57  82   89
座號30  60   85  94  88   90
座號31  73   71  99  63   60
座號32  83   89  69  60   55
座號33  82   71  52  62   81
座號34  61   79  77  86   94
座號35  58   87  85  99   85
座號36  95   68  52  73   69
座號37  87   93  75  66   99
座號38  87   54  97  52   73
座號39  56  100  93  76   86
座號40  50   60  78  54   51
座號41  90   93  70  62   59
座號42  60   84  58  74   81
座號43  85   90  72  59   62
座號44  77   71  71  66   82
座號45  98   63  81  73   93
座號46  80   97  76  62   72
座號47  84   59  81  59   66
座號48  66   81  59  89   86
座號49  71   84  69  70   91
座號50  93   78  81  63   93

In [6]:
def fun1(series:pd.Series)->pd.Series:
    data = [series.sum(),series.mean()]
    s = pd.Series(data,
                  index=['總分','平均'])
    return s

scores_df.apply(fun1,axis=1)

         總分    平均
座號
座號1   322.0  64.4
座號2   376.0  75.2
座號3   331.0  66.2
座號4   378.0  75.6
座號5   347.0  69.4
座號6   389.0  77.8
座號7   379.0  75.8
座號8   352.0  70.4
座號9   366.0  73.2
座號10  366.0  73.2
座號11  279.0  55.8
座號12  354.0  70.8
座號13  285.0  57.0
座號14  363.0  72.6
座號15  362.0  72.4
座號16  395.0  79.0
座號17  331.0  66.2
座號18  375.0  75.0
座號19  395.0  79.0
座號20  381.0  76.2
座號21  391.0  78.2
座號22  416.0  83.2
座號23  393.0  78.6
座號24  364.0  72.8
座號25  341.0  68.2
座號26  385.0  77.0
座號27  385.0  77.0
座號28  354.0  70.8
座號29  353.0  70.6
座號30  417.0  83.4
座號31  366.0  73.2
座號32  356.0  71.2
座號33  348.0  69.6
座號34  397.0  79.4
座號35  414.0  82.8
座號36  357.0  71.4
座號37  420.0  84.0
座號38  363.0  72.6
座號39  411.0  82.2
座號40  293.0  58.6
座號41  374.0  74.8
座號42  357.0  71.4
座號43  368.0  73.6
座號44  367.0  73.4
座號45  408.0  81.6
座號46  387.0  77.4
座號47  349.0  69.8
座號48  381.0  76.2
座號49  385.0  77.0
座號50  408.0  81.6

In [7]:
def fun2(series:pd.Series)->pd.Series:
    data = [series.sum(),series.mean(),series.max(),series.min()]
    s = pd.Series(data,
                  index=['總分','平均','最高分','最低分'])
    return s

scores_df.apply(fun2,axis=1)

         總分    平均    最高分   最低分
座號
座號1   322.0  64.4   86.0  50.0
座號2   376.0  75.2   98.0  50.0
座號3   331.0  66.2   87.0  50.0
座號4   378.0  75.6   95.0  53.0
座號5   347.0  69.4   93.0  52.0
座號6   389.0  77.8   97.0  55.0
座號7   379.0  75.8   86.0  56.0
座號8   352.0  70.4  100.0  51.0
座號9   366.0  73.2   95.0  50.0
座號10  366.0  73.2   96.0  62.0
座號11  279.0  55.8   64.0  52.0
座號12  354.0  70.8   93.0  53.0
座號13  285.0  57.0   60.0  51.0
座號14  363.0  72.6   95.0  55.0
座號15  362.0  72.4   89.0  60.0
座號16  395.0  79.0  100.0  54.0
座號17  331.0  66.2   82.0  50.0
座號18  375.0  75.0   90.0  55.0
座號19  395.0  79.0   95.0  55.0
座號20  381.0  76.2   98.0  53.0
座號21  391.0  78.2   97.0  54.0
座號22  416.0  83.2   98.0  63.0
座號23  393.0  78.6   99.0  55.0
座號24  364.0  72.8   95.0  54.0
座號25  341.0  68.2   89.0  51.0
座號26  385.0  77.0   90.0  63.0
座號27  385.0  77.0   98.0  52.0
座號28  354.0  70.8   83.0  63.0
座號29  353.0  70.6   89.0  57.0
座號30  417.0  83.4   94.0  60.0
座號31  366.0  73.2   99.0  60.0
座號32  356.0  71.2   89.0  55.0
座號33  348.0  69.6   82.0  52.0
座號34  397.0  79.4   94.0  61.0
座號35  414.0  82.8   99.0  58.0
座號36  357.0  71.4   95.0  52.0
座號37  420.0  84.0   99.0  66.0
座號38  363.0  72.6   97.0  52.0
座號39  411.0  82.2  100.0  56.0
座號40  293.0  58.6   78.0  50.0
座號41  374.0  74.8   93.0  59.0
座號42  357.0  71.4   84.0  58.0
座號43  368.0  73.6   90.0  59.0
座號44  367.0  73.4   82.0  66.0
座號45  408.0  81.6   98.0  63.0
座號46  387.0  77.4   97.0  62.0
座號47  349.0  69.8   84.0  59.0
座號48  381.0  76.2   89.0  59.0
座號49  385.0  77.0   91.0  69.0
座號50  408.0  81.6   93.0  63.0