In [1]:
import numpy as np
import pandas as pd

tips = pd.read_csv('tips.csv')
tips

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [2]:
tips.columns = ['總票價', '小費', '吸煙者', '日期', '時間', '大小']
tips

       總票價    小費  吸煙者    日期      時間  大小
0    16.99  1.01   No   Sun  Dinner   2
1    10.34  1.66   No   Sun  Dinner   3
2    21.01  3.50   No   Sun  Dinner   3
3    23.68  3.31   No   Sun  Dinner   2
4    24.59  3.61   No   Sun  Dinner   4
..     ...   ...  ...   ...     ...  ..
239  29.03  5.92   No   Sat  Dinner   3
240  27.18  2.00  Yes   Sat  Dinner   2
241  22.67  2.00  Yes   Sat  Dinner   2
242  17.82  1.75   No   Sat  Dinner   2
243  18.78  3.00   No  Thur  Dinner   2

[244 rows x 6 columns]

In [3]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   總票價     244 non-null    float64
 1   小費      244 non-null    float64
 2   吸煙者     244 non-null    object
 3   日期      244 non-null    object
 4   時間      244 non-null    object
 5   大小      244 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 11.6+ KB

In [5]:
tips['小費比例'] = tips['小費'] / tips['總票價']
tips

       總票價    小費  吸煙者    日期      時間  大小      小費比例
0    16.99  1.01   No   Sun  Dinner   2  0.059447
1    10.34  1.66   No   Sun  Dinner   3  0.160542
2    21.01  3.50   No   Sun  Dinner   3  0.166587
3    23.68  3.31   No   Sun  Dinner   2  0.139780
4    24.59  3.61   No   Sun  Dinner   4  0.146808
..     ...   ...  ...   ...     ...  ..       ...
239  29.03  5.92   No   Sat  Dinner   3  0.203927
240  27.18  2.00  Yes   Sat  Dinner   2  0.073584
241  22.67  2.00  Yes   Sat  Dinner   2  0.088222
242  17.82  1.75   No   Sat  Dinner   2  0.098204
243  18.78  3.00   No  Thur  Dinner   2  0.159744

[244 rows x 7 columns]

In [7]:
grouped = tips.groupby(by=['日期','吸煙者'])
len(grouped)

8

In [8]:
dict(list(grouped))

{('Fri',
  'No'):        總票價    小費 吸煙者   日期      時間  大小      小費比例
 91   22.49  3.50  No  Fri  Dinner   2  0.155625
 94   22.75  3.25  No  Fri  Dinner   2  0.142857
 99   12.46  1.50  No  Fri  Dinner   2  0.120385
 223  15.98  3.00  No  Fri   Lunch   3  0.187735,
 ('Fri',
  'Yes'):        總票價    小費  吸煙者   日期      時間  大小      小費比例
 90   28.97  3.00  Yes  Fri  Dinner   2  0.103555
 92    5.75  1.00  Yes  Fri  Dinner   2  0.173913
 93   16.32  4.30  Yes  Fri  Dinner   2  0.263480
 95   40.17  4.73  Yes  Fri  Dinner   4  0.117750
 96   27.28  4.00  Yes  Fri  Dinner   2  0.146628
 97   12.03  1.50  Yes  Fri  Dinner   2  0.124688
 98   21.01  3.00  Yes  Fri  Dinner   2  0.142789
 100  11.35  2.50  Yes  Fri  Dinner   2  0.220264
 101  15.38  3.00  Yes  Fri  Dinner   2  0.195059
 220  12.16  2.20  Yes  Fri   Lunch   2  0.180921
 221  13.42  3.48  Yes  Fri   Lunch   2  0.259314
 222   8.58  1.92  Yes  Fri   Lunch   1  0.223776
 224  13.42  1.58  Yes  Fri   Lunch   2  0.117735
 225  16.27  2.50  Yes  Fri   Lunch   2  0.153657
 226  10.09  2.00  Yes  Fri   Lunch   2  0.198216,
 ('Sat',
  'No'):        總票價    小費 吸煙者   日期      時間  大小      小費比例
 19   20.65  3.35  No  Sat  Dinner   3  0.162228
 20   17.92  4.08  No  Sat  Dinner   2  0.227679
 21   20.29  2.75  No  Sat  Dinner   2  0.135535
 22   15.77  2.23  No  Sat  Dinner   2  0.141408
 23   39.42  7.58  No  Sat  Dinner   4  0.192288
 24   19.82  3.18  No  Sat  Dinner   2  0.160444
 25   17.81  2.34  No  Sat  Dinner   4  0.131387
 26   13.37  2.00  No  Sat  Dinner   2  0.149589
 27   12.69  2.00  No  Sat  Dinner   2  0.157604
 28   21.70  4.30  No  Sat  Dinner   2  0.198157
 29   19.65  3.00  No  Sat  Dinner   2  0.152672
 30    9.55  1.45  No  Sat  Dinner   2  0.151832
 31   18.35  2.50  No  Sat  Dinner   4  0.136240
 32   15.06  3.00  No  Sat  Dinner   2  0.199203
 33   20.69  2.45  No  Sat  Dinner   4  0.118415
 34   17.78  3.27  No  Sat  Dinner   2  0.183915
 35   24.06  3.60  No  Sat  Dinner   3  0.149626
 36   16.31  2.00  No  Sat  Dinner   3  0.122624
 37   16.93  3.07  No  Sat  Dinner   3  0.181335
 38   18.69  2.31  No  Sat  Dinner   3  0.123596
 39   31.27  5.00  No  Sat  Dinner   3  0.159898
 40   16.04  2.24  No  Sat  Dinner   3  0.139651
 57   26.41  1.50  No  Sat  Dinner   2  0.056797
 59   48.27  6.73  No  Sat  Dinner   4  0.139424
 64   17.59  2.64  No  Sat  Dinner   3  0.150085
 65   20.08  3.15  No  Sat  Dinner   3  0.156873
 66   16.45  2.47  No  Sat  Dinner   2  0.150152
 68   20.23  2.01  No  Sat  Dinner   2  0.099357
 70   12.02  1.97  No  Sat  Dinner   2  0.163894
 71   17.07  3.00  No  Sat  Dinner   3  0.175747
 74   14.73  2.20  No  Sat  Dinner   2  0.149355
 75   10.51  1.25  No  Sat  Dinner   2  0.118934
 104  20.92  4.08  No  Sat  Dinner   2  0.195029
 108  18.24  3.76  No  Sat  Dinner   2  0.206140
 110  14.00  3.00  No  Sat  Dinner   2  0.214286
 111   7.25  1.00  No  Sat  Dinner   1  0.137931
 212  48.33  9.00  No  Sat  Dinner   4  0.186220
 227  20.45  3.00  No  Sat  Dinner   4  0.146699
 228  13.28  2.72  No  Sat  Dinner   2  0.204819
 232  11.61  3.39  No  Sat  Dinner   2  0.291990
 233  10.77  1.47  No  Sat  Dinner   2  0.136490
 235  10.07  1.25  No  Sat  Dinner   2  0.124131
 238  35.83  4.67  No  Sat  Dinner   3  0.130338
 239  29.03  5.92  No  Sat  Dinner   3  0.203927
 242  17.82  1.75  No  Sat  Dinner   2  0.098204,
 ('Sat',
  'Yes'):        總票價     小費  吸煙者   日期      時間  大小      小費比例
 56   38.01   3.00  Yes  Sat  Dinner   4  0.078927
 58   11.24   1.76  Yes  Sat  Dinner   2  0.156584
 60   20.29   3.21  Yes  Sat  Dinner   2  0.158206
 61   13.81   2.00  Yes  Sat  Dinner   2  0.144823
 62   11.02   1.98  Yes  Sat  Dinner   2  0.179673
 63   18.29   3.76  Yes  Sat  Dinner   4  0.205577
 67    3.07   1.00  Yes  Sat  Dinner   1  0.325733
 69   15.01   2.09  Yes  Sat  Dinner   2  0.139241
 72   26.86   3.14  Yes  Sat  Dinner   2  0.116902
 73   25.28   5.00  Yes  Sat  Dinner   2  0.197785
 76   17.92   3.08  Yes  Sat  Dinner   2  0.171875
 102  44.30   2.50  Yes  Sat  Dinner   3  0.056433
 103  22.42   3.48  Yes  Sat  Dinner   2  0.155219
 105  15.36   1.64  Yes  Sat  Dinner   2  0.106771
 106  20.49   4.06  Yes  Sat  Dinner   2  0.198145
 107  25.21   4.29  Yes  Sat  Dinner   2  0.170171
 109  14.31   4.00  Yes  Sat  Dinner   2  0.279525
 168  10.59   1.61  Yes  Sat  Dinner   2  0.152030
 169  10.63   2.00  Yes  Sat  Dinner   2  0.188147
 170  50.81  10.00  Yes  Sat  Dinner   3  0.196812
 171  15.81   3.16  Yes  Sat  Dinner   2  0.199873
 206  26.59   3.41  Yes  Sat  Dinner   3  0.128244
 207  38.73   3.00  Yes  Sat  Dinner   4  0.077459
 208  24.27   2.03  Yes  Sat  Dinner   2  0.083642
 209  12.76   2.23  Yes  Sat  Dinner   2  0.174765
 210  30.06   2.00  Yes  Sat  Dinner   3  0.066534
 211  25.89   5.16  Yes  Sat  Dinner   4  0.199305
 213  13.27   2.50  Yes  Sat  Dinner   2  0.188395
 214  28.17   6.50  Yes  Sat  Dinner   3  0.230742
 215  12.90   1.10  Yes  Sat  Dinner   2  0.085271
 216  28.15   3.00  Yes  Sat  Dinner   5  0.106572
 217  11.59   1.50  Yes  Sat  Dinner   2  0.129422
 218   7.74   1.44  Yes  Sat  Dinner   2  0.186047
 219  30.14   3.09  Yes  Sat  Dinner   4  0.102522
 229  22.12   2.88  Yes  Sat  Dinner   2  0.130199
 230  24.01   2.00  Yes  Sat  Dinner   4  0.083299
 231  15.69   3.00  Yes  Sat  Dinner   3  0.191205
 234  15.53   3.00  Yes  Sat  Dinner   2  0.193175
 236  12.60   1.00  Yes  Sat  Dinner   2  0.079365
 237  32.83   1.17  Yes  Sat  Dinner   2  0.035638
 240  27.18   2.00  Yes  Sat  Dinner   2  0.073584
 241  22.67   2.00  Yes  Sat  Dinner   2  0.088222,
 ('Sun',
  'No'):        總票價    小費 吸煙者   日期      時間  大小      小費比例
 0    16.99  1.01  No  Sun  Dinner   2  0.059447
 1    10.34  1.66  No  Sun  Dinner   3  0.160542
 2    21.01  3.50  No  Sun  Dinner   3  0.166587
 3    23.68  3.31  No  Sun  Dinner   2  0.139780
 4    24.59  3.61  No  Sun  Dinner   4  0.146808
 5    25.29  4.71  No  Sun  Dinner   4  0.186240
 6     8.77  2.00  No  Sun  Dinner   2  0.228050
 7    26.88  3.12  No  Sun  Dinner   4  0.116071
 8    15.04  1.96  No  Sun  Dinner   2  0.130319
 9    14.78  3.23  No  Sun  Dinner   2  0.218539
 10   10.27  1.71  No  Sun  Dinner   2  0.166504
 11   35.26  5.00  No  Sun  Dinner   4  0.141804
 12   15.42  1.57  No  Sun  Dinner   2  0.101816
 13   18.43  3.00  No  Sun  Dinner   4  0.162778
 14   14.83  3.02  No  Sun  Dinner   2  0.203641
 15   21.58  3.92  No  Sun  Dinner   2  0.181650
 16   10.33  1.67  No  Sun  Dinner   3  0.161665
 17   16.29  3.71  No  Sun  Dinner   3  0.227747
 18   16.97  3.50  No  Sun  Dinner   3  0.206246
 41   17.46  2.54  No  Sun  Dinner   2  0.145475
 42   13.94  3.06  No  Sun  Dinner   2  0.219512
 43    9.68  1.32  No  Sun  Dinner   2  0.136364
 44   30.40  5.60  No  Sun  Dinner   4  0.184211
 45   18.29  3.00  No  Sun  Dinner   2  0.164024
 46   22.23  5.00  No  Sun  Dinner   2  0.224921
 47   32.40  6.00  No  Sun  Dinner   4  0.185185
 48   28.55  2.05  No  Sun  Dinner   3  0.071804
 49   18.04  3.00  No  Sun  Dinner   2  0.166297
 50   12.54  2.50  No  Sun  Dinner   2  0.199362
 51   10.29  2.60  No  Sun  Dinner   2  0.252672
 52   34.81  5.20  No  Sun  Dinner   4  0.149382
 53    9.94  1.56  No  Sun  Dinner   2  0.156942
 54   25.56  4.34  No  Sun  Dinner   4  0.169797
 55   19.49  3.51  No  Sun  Dinner   2  0.180092
 112  38.07  4.00  No  Sun  Dinner   3  0.105070
 113  23.95  2.55  No  Sun  Dinner   2  0.106472
 114  25.71  4.00  No  Sun  Dinner   3  0.155581
 115  17.31  3.50  No  Sun  Dinner   2  0.202195
 116  29.93  5.07  No  Sun  Dinner   4  0.169395
 150  14.07  2.50  No  Sun  Dinner   2  0.177683
 151  13.13  2.00  No  Sun  Dinner   2  0.152323
 152  17.26  2.74  No  Sun  Dinner   3  0.158749
 153  24.55  2.00  No  Sun  Dinner   4  0.081466
 154  19.77  2.00  No  Sun  Dinner   4  0.101163
 155  29.85  5.14  No  Sun  Dinner   5  0.172194
 156  48.17  5.00  No  Sun  Dinner   6  0.103799
 157  25.00  3.75  No  Sun  Dinner   4  0.150000
 158  13.39  2.61  No  Sun  Dinner   2  0.194922
 159  16.49  2.00  No  Sun  Dinner   4  0.121286
 160  21.50  3.50  No  Sun  Dinner   4  0.162791
 161  12.66  2.50  No  Sun  Dinner   2  0.197472
 162  16.21  2.00  No  Sun  Dinner   3  0.123381
 163  13.81  2.00  No  Sun  Dinner   2  0.144823
 165  24.52  3.48  No  Sun  Dinner   3  0.141925
 166  20.76  2.24  No  Sun  Dinner   2  0.107900
 167  31.71  4.50  No  Sun  Dinner   4  0.141911
 185  20.69  5.00  No  Sun  Dinner   5  0.241663,
 ('Sun',
  'Yes'):        總票價    小費  吸煙者   日期      時間  大小      小費比例
 164  17.51  3.00  Yes  Sun  Dinner   2  0.171331
 172   7.25  5.15  Yes  Sun  Dinner   2  0.710345
 173  31.85  3.18  Yes  Sun  Dinner   2  0.099843
 174  16.82  4.00  Yes  Sun  Dinner   2  0.237812
 175  32.90  3.11  Yes  Sun  Dinner   2  0.094529
 176  17.89  2.00  Yes  Sun  Dinner   2  0.111794
 177  14.48  2.00  Yes  Sun  Dinner   2  0.138122
 178   9.60  4.00  Yes  Sun  Dinner   2  0.416667
 179  34.63  3.55  Yes  Sun  Dinner   2  0.102512
 180  34.65  3.68  Yes  Sun  Dinner   4  0.106205
 181  23.33  5.65  Yes  Sun  Dinner   2  0.242177
 182  45.35  3.50  Yes  Sun  Dinner   3  0.077178
 183  23.17  6.50  Yes  Sun  Dinner   4  0.280535
 184  40.55  3.00  Yes  Sun  Dinner   2  0.073983
 186  20.90  3.50  Yes  Sun  Dinner   3  0.167464
 187  30.46  2.00  Yes  Sun  Dinner   5  0.065660
 188  18.15  3.50  Yes  Sun  Dinner   3  0.192837
 189  23.10  4.00  Yes  Sun  Dinner   3  0.173160
 190  15.69  1.50  Yes  Sun  Dinner   2  0.095602,
 ('Thur',
  'No'):        總票價    小費 吸煙者    日期      時間  大小      小費比例
 77   27.20  4.00  No  Thur   Lunch   4  0.147059
 78   22.76  3.00  No  Thur   Lunch   2  0.131810
 79   17.29  2.71  No  Thur   Lunch   2  0.156738
 81   16.66  3.40  No  Thur   Lunch   2  0.204082
 82   10.07  1.83  No  Thur   Lunch   1  0.181728
 84   15.98  2.03  No  Thur   Lunch   2  0.127034
 85   34.83  5.17  No  Thur   Lunch   4  0.148435
 86   13.03  2.00  No  Thur   Lunch   2  0.153492
 87   18.28  4.00  No  Thur   Lunch   2  0.218818
 88   24.71  5.85  No  Thur   Lunch   2  0.236746
 89   21.16  3.00  No  Thur   Lunch   2  0.141777
 117  10.65  1.50  No  Thur   Lunch   2  0.140845
 118  12.43  1.80  No  Thur   Lunch   2  0.144811
 119  24.08  2.92  No  Thur   Lunch   4  0.121262
 120  11.69  2.31  No  Thur   Lunch   2  0.197605
 121  13.42  1.68  No  Thur   Lunch   2  0.125186
 122  14.26  2.50  No  Thur   Lunch   2  0.175316
 123  15.95  2.00  No  Thur   Lunch   2  0.125392
 124  12.48  2.52  No  Thur   Lunch   2  0.201923
 125  29.80  4.20  No  Thur   Lunch   6  0.140940
 126   8.52  1.48  No  Thur   Lunch   2  0.173709
 127  14.52  2.00  No  Thur   Lunch   2  0.137741
 128  11.38  2.00  No  Thur   Lunch   2  0.175747
 129  22.82  2.18  No  Thur   Lunch   3  0.095530
 130  19.08  1.50  No  Thur   Lunch   2  0.078616
 131  20.27  2.83  No  Thur   Lunch   2  0.139615
 132  11.17  1.50  No  Thur   Lunch   2  0.134288
 133  12.26  2.00  No  Thur   Lunch   2  0.163132
 134  18.26  3.25  No  Thur   Lunch   2  0.177985
 135   8.51  1.25  No  Thur   Lunch   2  0.146886
 136  10.33  2.00  No  Thur   Lunch   2  0.193611
 137  14.15  2.00  No  Thur   Lunch   2  0.141343
 139  13.16  2.75  No  Thur   Lunch   2  0.208967
 140  17.47  3.50  No  Thur   Lunch   2  0.200343
 141  34.30  6.70  No  Thur   Lunch   6  0.195335
 142  41.19  5.00  No  Thur   Lunch   5  0.121389
 143  27.05  5.00  No  Thur   Lunch   6  0.184843
 144  16.43  2.30  No  Thur   Lunch   2  0.139988
 145   8.35  1.50  No  Thur   Lunch   2  0.179641
 146  18.64  1.36  No  Thur   Lunch   3  0.072961
 147  11.87  1.63  No  Thur   Lunch   2  0.137321
 148   9.78  1.73  No  Thur   Lunch   2  0.176892
 149   7.51  2.00  No  Thur   Lunch   2  0.266312
 195   7.56  1.44  No  Thur   Lunch   2  0.190476
 243  18.78  3.00  No  Thur  Dinner   2  0.159744,
 ('Thur',
  'Yes'):        總票價    小費  吸煙者    日期     時間  大小      小費比例
 80   19.44  3.00  Yes  Thur  Lunch   2  0.154321
 83   32.68  5.00  Yes  Thur  Lunch   2  0.152999
 138  16.00  2.00  Yes  Thur  Lunch   2  0.125000
 191  19.81  4.19  Yes  Thur  Lunch   2  0.211509
 192  28.44  2.56  Yes  Thur  Lunch   2  0.090014
 193  15.48  2.02  Yes  Thur  Lunch   2  0.130491
 194  16.58  4.00  Yes  Thur  Lunch   2  0.241255
 196  10.34  2.00  Yes  Thur  Lunch   2  0.193424
 197  43.11  5.00  Yes  Thur  Lunch   4  0.115982
 198  13.00  2.00  Yes  Thur  Lunch   2  0.153846
 199  13.51  2.00  Yes  Thur  Lunch   2  0.148038
 200  18.71  4.00  Yes  Thur  Lunch   3  0.213789
 201  12.74  2.01  Yes  Thur  Lunch   2  0.157771
 202  13.00  2.00  Yes  Thur  Lunch   2  0.153846
 203  16.40  2.50  Yes  Thur  Lunch   2  0.152439
 204  20.53  4.00  Yes  Thur  Lunch   4  0.194837
 205  16.47  3.23  Yes  Thur  Lunch   3  0.196114}

In [11]:
grouped_pct = grouped['小費']
display(grouped_pct.agg('mean'))
grouped_pct.agg('mean').unstack()

日期    吸煙者
Fri   No     2.812500
      Yes    2.714000
Sat   No     3.102889
      Yes    2.875476
Sun   No     3.167895
      Yes    3.516842
Thur  No     2.673778
      Yes    3.030000
Name: 小費, dtype: float64

吸煙者         No       Yes
日期
Fri   2.812500  2.714000
Sat   3.102889  2.875476
Sun   3.167895  3.516842
Thur  2.673778  3.030000